export type ThemeOption = { label: string; value: string };

export const THEMES_BY_AGE: Record<string, ThemeOption[]> = {
  "2": [
    { label: "Saying goodnight", value: "saying goodnight" },
    { label: "Sharing toys", value: "sharing toys" },
    { label: "Eating vegetables", value: "eating vegetables" },
    { label: "Feeling scared", value: "feeling scared" },
    { label: "Bath time fun", value: "bath time fun" },
    { label: "Hugging Mamma", value: "hugging mamma" },
    { label: "My first friend", value: "my first friend" },
    { label: "Finding colours", value: "finding colours" },
    { label: "Baby animals", value: "baby animals" },
    { label: "Oops, I spilled!", value: "oops i spilled" },
    { label: "One more bite", value: "one more bite" },
    { label: "Sleepy train", value: "sleepy train" },
  ],
  "3": [
    { label: "Taking turns", value: "taking turns" },
    { label: "Fruits are yummy", value: "fruits are yummy" },
    { label: "Bedtime monsters", value: "bedtime monsters" },
    { label: "I feel angry", value: "i feel angry" },
    { label: "New baby sibling", value: "new baby sibling" },
    { label: "Why is the sky blue?", value: "why is the sky blue" },
    { label: "Being brave", value: "being brave" },
    { label: "I can do it myself", value: "i can do it myself" },
    { label: "Saying sorry", value: "saying sorry" },
    { label: "Papa comes home", value: "papa comes home" },
    { label: "Rain and puddles", value: "rain and puddles" },
    { label: "Quiet time", value: "quiet time" },
  ],
  "4": [
    { label: "First day of school", value: "first day of school" },
    { label: "Making a new friend", value: "making a new friend" },
    { label: "Healthy lunchbox", value: "healthy lunchbox" },
    { label: "Bedtime and stars", value: "bedtime and stars" },
    { label: "Feeling left out", value: "feeling left out" },
    { label: "Bugs and butterflies", value: "bugs and butterflies" },
    { label: "Grandma's house", value: "grandmas house" },
    { label: "Being honest", value: "being honest" },
    { label: "I fell down", value: "i fell down" },
    { label: "Mixing colours", value: "mixing colours" },
    { label: "Missing Mamma", value: "missing mamma" },
    { label: "Try one more time", value: "try one more time" },
  ],
  "5": [
    { label: "Friendship", value: "friendship" },
    { label: "Courage", value: "courage" },
    { label: "Healthy eating", value: "healthy eating" },
    { label: "Sleep routine", value: "sleep routine" },
    { label: "Sharing", value: "sharing" },
    { label: "Kindness", value: "kindness" },
    { label: "Curiosity", value: "curiosity" },
    { label: "Family love", value: "family love" },
    { label: "Understanding feelings", value: "understanding feelings" },
    { label: "Trying new things", value: "trying new things" },
    { label: "Nature and seasons", value: "nature and seasons" },
    { label: "Helping at home", value: "helping at home" },
  ],
  "6": [
    { label: "Standing up for others", value: "standing up for others" },
    { label: "Losing gracefully", value: "losing gracefully" },
    { label: "Eating a rainbow", value: "eating a rainbow" },
    { label: "Dreams and nightmares", value: "dreams and nightmares" },
    { label: "When friends fight", value: "when friends fight" },
    { label: "How things work", value: "how things work" },
    { label: "Being responsible", value: "being responsible" },
    { label: "Different families", value: "different families" },
    { label: "The new kid", value: "the new kid" },
    { label: "Apologising properly", value: "apologising properly" },
    { label: "Plants and growing", value: "plants and growing" },
    { label: "Weekend with Nana", value: "weekend with nana" },
  ],
  "7": [
    { label: "Fairness and justice", value: "fairness and justice" },
    { label: "Trying when it's hard", value: "trying when its hard" },
    { label: "Where food comes from", value: "where food comes from" },
    { label: "Worry at bedtime", value: "worry at bedtime" },
    { label: "Jealousy", value: "jealousy" },
    { label: "Science experiments", value: "science experiments" },
    { label: "Moving to a new place", value: "moving to a new place" },
    { label: "Grandparent stories", value: "grandparent stories" },
    { label: "Keeping a secret vs telling", value: "keeping vs telling" },
    { label: "When I feel lonely", value: "when i feel lonely" },
    { label: "Night sky and planets", value: "night sky and planets" },
    { label: "Pet care", value: "pet care" },
  ],
  "8": [
    { label: "Peer pressure", value: "peer pressure" },
    { label: "Lying and its consequences", value: "lying and consequences" },
    { label: "Body and food choices", value: "body and food choices" },
    { label: "Screen time at night", value: "screen time at night" },
    { label: "Bullying", value: "bullying" },
    { label: "How the world was made", value: "how the world was made" },
    { label: "Failure and trying again", value: "failure and trying again" },
    { label: "Working parents", value: "working parents" },
    { label: "Inclusion", value: "inclusion" },
    { label: "Mixed-up feelings", value: "mixed-up feelings" },
    { label: "Ancient civilisations", value: "ancient civilisations" },
    { label: "Traditions and culture", value: "traditions and culture" },
  ],
  "9": [
    { label: "Standing up to a friend", value: "standing up to a friend" },
    { label: "Waste and environment", value: "waste and environment" },
    { label: "Sleep and performance", value: "sleep and performance" },
    { label: "Online kindness", value: "online kindness" },
    { label: "Grief and loss", value: "grief and loss" },
    { label: "Inventions and discoveries", value: "inventions and discoveries" },
    { label: "Identity and belonging", value: "identity and belonging" },
    { label: "Gender and stereotypes", value: "gender and stereotypes" },
    { label: "Anger management", value: "anger management" },
    { label: "Climate and responsibility", value: "climate and responsibility" },
    { label: "Distant family", value: "distant family" },
    { label: "When adults are wrong", value: "when adults are wrong" },
  ],
  "10": [
    { label: "Ambition vs friendship", value: "ambition vs friendship" },
    { label: "Nutrition and growing", value: "nutrition and growing" },
    { label: "Stress and rest", value: "stress and rest" },
    { label: "Moral dilemmas", value: "moral dilemmas" },
    { label: "Social media pressure", value: "social media pressure" },
    { label: "How money works", value: "how money works" },
    { label: "Blended families", value: "blended families" },
    { label: "Environmental activism", value: "environmental activism" },
    { label: "Comparing yourself to others", value: "comparing yourself" },
    { label: "Cultural heritage", value: "cultural heritage" },
    { label: "Loyalty and honesty", value: "loyalty and honesty" },
    { label: "Becoming yourself", value: "becoming yourself" },
  ],
};

export const CUSTOM_THEME_VALUE = "__custom";

export function getThemeOptions(age: number | string): ThemeOption[] {
  const n = typeof age === "number" ? age : parseInt(String(age), 10);
  if (!Number.isFinite(n)) return [];
  const key = String(n);
  return THEMES_BY_AGE[key] ?? [];
}
