-- Backfill: force every personalised/bedtime story's thumbnail
-- to match the theme -> emoji map in src/lib/themeEmoji.ts.
--
-- Admin-uploaded pre_recorded stories are intentionally left untouched.
--
-- Run this in your own Supabase project's SQL editor.

UPDATE public.stories
SET thumbnail = CASE lower(btrim(theme))
  -- Age 2
  WHEN 'saying goodnight' THEN '🌙'
  WHEN 'sharing toys' THEN '🧸'
  WHEN 'eating vegetables' THEN '🥦'
  WHEN 'feeling scared' THEN '🫶'
  WHEN 'bath time fun' THEN '🛁'
  WHEN 'hugging mamma' THEN '🤗'
  WHEN 'my first friend' THEN '🤝'
  WHEN 'finding colours' THEN '🌈'
  WHEN 'baby animals' THEN '🐣'
  WHEN 'oops, i spilled!' THEN '💧'
  WHEN 'one more bite' THEN '🍓'
  WHEN 'sleepy train' THEN '🚂'
  -- Age 3
  WHEN 'taking turns' THEN '🔄'
  WHEN 'fruits are yummy' THEN '🍉'
  WHEN 'bedtime monsters' THEN '👾'
  WHEN 'i feel angry' THEN '😤'
  WHEN 'new baby sibling' THEN '👶'
  WHEN 'why is the sky blue?' THEN '☁️'
  WHEN 'being brave' THEN '⚡'
  WHEN 'i can do it myself' THEN '💪'
  WHEN 'saying sorry' THEN '🙏'
  WHEN 'papa comes home' THEN '🏡'
  WHEN 'rain and puddles' THEN '🌧️'
  WHEN 'quiet time' THEN '🤫'
  -- Age 4
  WHEN 'first day of school' THEN '🎒'
  WHEN 'making a new friend' THEN '🤝'
  WHEN 'healthy lunchbox' THEN '🥗'
  WHEN 'bedtime and stars' THEN '⭐'
  WHEN 'feeling left out' THEN '🫂'
  WHEN 'bugs and butterflies' THEN '🦋'
  WHEN 'grandma''s house' THEN '🏡'
  WHEN 'being honest' THEN '🪞'
  WHEN 'i fell down' THEN '🌱'
  WHEN 'mixing colours' THEN '🎨'
  WHEN 'missing mamma' THEN '💛'
  WHEN 'try one more time' THEN '🏅'
  -- Age 5
  WHEN 'friendship' THEN '🤝'
  WHEN 'courage' THEN '⚡'
  WHEN 'healthy eating' THEN '🥗'
  WHEN 'sleep routine' THEN '🌙'
  WHEN 'sharing' THEN '🎁'
  WHEN 'kindness' THEN '💛'
  WHEN 'curiosity' THEN '🔭'
  WHEN 'family love' THEN '🏡'
  WHEN 'understanding feelings' THEN '🫶'
  WHEN 'trying new things' THEN '🌱'
  WHEN 'nature and seasons' THEN '🍃'
  WHEN 'helping at home' THEN '🧹'
  -- Age 6
  WHEN 'standing up for others' THEN '🦁'
  WHEN 'losing gracefully' THEN '🏆'
  WHEN 'eating a rainbow' THEN '🌈'
  WHEN 'dreams and nightmares' THEN '💭'
  WHEN 'when friends fight' THEN '🤝'
  WHEN 'how things work' THEN '⚙️'
  WHEN 'being responsible' THEN '✅'
  WHEN 'different families' THEN '👨‍👩‍👧'
  WHEN 'the new kid' THEN '🎒'
  WHEN 'apologising properly' THEN '🙏'
  WHEN 'plants and growing' THEN '🌿'
  WHEN 'weekend with nana' THEN '👵'
  -- Age 7
  WHEN 'fairness and justice' THEN '⚖️'
  WHEN 'trying when it''s hard' THEN '🏅'
  WHEN 'where food comes from' THEN '🌾'
  WHEN 'worry at bedtime' THEN '🌙'
  WHEN 'jealousy' THEN '💚'
  WHEN 'science experiments' THEN '🔬'
  WHEN 'moving to a new place' THEN '📦'
  WHEN 'grandparent stories' THEN '👴'
  WHEN 'keeping a secret vs telling' THEN '🤐'
  WHEN 'when i feel lonely' THEN '🫂'
  WHEN 'night sky and planets' THEN '🪐'
  WHEN 'pet care' THEN '🐾'
  -- Age 8
  WHEN 'peer pressure' THEN '🧭'
  WHEN 'lying and its consequences' THEN '🪞'
  WHEN 'body and food choices' THEN '🥗'
  WHEN 'screen time at night' THEN '📵'
  WHEN 'bullying' THEN '🦁'
  WHEN 'how the world was made' THEN '🌍'
  WHEN 'failure and trying again' THEN '🌱'
  WHEN 'working parents' THEN '💼'
  WHEN 'inclusion' THEN '🫂'
  WHEN 'mixed-up feelings' THEN '🌀'
  WHEN 'ancient civilisations' THEN '🏛️'
  WHEN 'traditions and culture' THEN '🪔'
  -- Age 9
  WHEN 'standing up to a friend' THEN '🦁'
  WHEN 'waste and environment' THEN '♻️'
  WHEN 'sleep and performance' THEN '🌙'
  WHEN 'online kindness' THEN '💛'
  WHEN 'grief and loss' THEN '🕊️'
  WHEN 'inventions and discoveries' THEN '💡'
  WHEN 'identity and belonging' THEN '🫂'
  WHEN 'gender and stereotypes' THEN '🌈'
  WHEN 'anger management' THEN '🌊'
  WHEN 'climate and responsibility' THEN '🌍'
  WHEN 'distant family' THEN '✉️'
  WHEN 'when adults are wrong' THEN '⚖️'
  -- Age 10
  WHEN 'ambition vs friendship' THEN '🤝'
  WHEN 'nutrition and growing' THEN '🥗'
  WHEN 'stress and rest' THEN '🌿'
  WHEN 'moral dilemmas' THEN '⚖️'
  WHEN 'social media pressure' THEN '📱'
  WHEN 'how money works' THEN '🪙'
  WHEN 'blended families' THEN '🏡'
  WHEN 'environmental activism' THEN '🌍'
  WHEN 'comparing yourself to others' THEN '🪞'
  WHEN 'cultural heritage' THEN '🪔'
  WHEN 'loyalty and honesty' THEN '🤝'
  WHEN 'becoming yourself' THEN '🌱'
  ELSE '📖'
END
WHERE story_type IN ('personalised_audio', 'bedtime_text');
